[project]
name = "stacks-finance"
description = ""
authors = []
telemetry = true
cache_dir = "./.cache"

# [contracts.counter]
# path = "contracts/counter.clar"
# epoch = "latest"

[contracts.governance]
path = "contracts/governance.clar"
epoch = "3.2"

[contracts.vault-registry]
path = "contracts/vault-registry.clar"
epoch = "3.2"

[contracts.vault-core]
path = "contracts/vault-core.clar"
epoch = "3.2"

[contracts.strategy-manager]
path = "contracts/strategy-manager.clar"
epoch = "3.2"

[contracts.strategy-lending]
path = "contracts/strategy-lending.clar"
epoch = "3.2"

[contracts.strategy-liquidity]
path = "contracts/strategy-liquidity.clar"
epoch = "3.2"

[contracts.strategy-income]
path = "contracts/strategy-income.clar"
epoch = "3.2"

[contracts.fee-manager]
path = "contracts/fee-manager.clar"
epoch = "3.2"

[contracts.oracle-nav]
path = "contracts/oracle-nav.clar"
epoch = "3.2"

[contracts.mock-token]
path = "contracts/mock-token.clar"
epoch = "3.2"

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }

# Check-checker settings:
# trusted_sender: if true, inputs are trusted after tx_sender has been checked.
# trusted_caller: if true, inputs are trusted after contract-caller has been checked.
# callee_filter: if true, untrusted data may be passed into a private function without a
# warning, if it gets checked inside. This check will also propagate up to the
# caller.
# More informations: https://www.hiro.so/blog/new-safety-checks-in-clarinet
