[project]
name = "stacks-finance"
description = ""
authors = []
telemetry = true
cache_dir = "./.cache"

# [contracts.counter]
# path = "contracts/counter.clar"
# epoch = "latest"

[contracts.governance-v2-v2601221844]
path = "contracts/governance-v2-v2601221844.clar"
epoch = "3.2"

[contracts.vault-registry-v2601221844]
path = "contracts/vault-registry-v2601221844.clar"
epoch = "3.2"

[contracts.vault-core-v2601221844]
path = "contracts/vault-core-v2601221844.clar"
epoch = "3.2"

[contracts.strategy-manager-v2601221844]
path = "contracts/strategy-manager-v2601221844.clar"
epoch = "3.2"

[contracts.strategy-lending-v2601221844]
path = "contracts/strategy-lending-v2601221844.clar"
epoch = "3.2"

[contracts.strategy-liquidity-v2601221844]
path = "contracts/strategy-liquidity-v2601221844.clar"
epoch = "3.2"

[contracts.strategy-income-v2601221844]
path = "contracts/strategy-income-v2601221844.clar"
epoch = "3.2"

[contracts.fee-manager-v2-v2601221844]
path = "contracts/fee-manager-v2-v2601221844.clar"
epoch = "3.2"

[contracts.oracle-nav-v2601221844]
path = "contracts/oracle-nav-v2601221844.clar"
epoch = "3.2"

[contracts.mock-token-v2-v2601221844]
path = "contracts/mock-token-v2-v2601221844.clar"
epoch = "3.2"

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }

# Check-checker settings:
# trusted_sender: if true, inputs are trusted after tx_sender has been checked.
# trusted_caller: if true, inputs are trusted after contract-caller has been checked.
# callee_filter: if true, untrusted data may be passed into a private function without a
# warning, if it gets checked inside. This check will also propagate up to the
# caller.
# More informations: https://www.hiro.so/blog/new-safety-checks-in-clarinet



